/* This component is not made by me, but generated by CHAT-GPT */

let interval;

export function countdown(targetDate) {
  const targetDateTime = new Date(targetDate);
  const countdownElement = document.createElement("span");

  function updateCountdown() {
    const currentTime = new Date().getTime();
    const timeRemaining = targetDateTime - currentTime;

    if (timeRemaining <= 0) {
      countdownElement.textContent = "Countdown expired!";
      clearInterval(interval);
    } else {
      const days = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));
      const hours = Math.floor(
        (timeRemaining % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
      );
      const minutes = Math.floor(
        (timeRemaining % (1000 * 60 * 60)) / (1000 * 60)
      );
      const seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);

      countdownElement.textContent = `Countdown: ${days} days, ${hours} hours, ${minutes} minutes, ${seconds} seconds`;
    }
  }
  updateCountdown();

  return countdownElement;
}
